### ISSUE TITLE
Failed to find LIBgui

### ISSUE THREAD

**Issue by AzureMonument** [franiscoder/dark-enchanting#11]
![image](https://user-images.githubusercontent.com/43318292/125669808-b6a4352e-7691-491d-8aea-5d3efd3b3c83.png)

Going to LibGui's site says players shouldn't download it and it should only be embedded, and it also says it is embedded on curseforge.
Currently running mc 1.17, fabric 0.11.6, and Dark Enchanting 0.4.0

**Comment by frqnny** [comment]
conc i will see into this

**Comment by frqnny** [comment]
Try the newest dark enchanting release (0.4.1)
