### ISSUE TITLE
Enchanting an item with an enchantment it already has a level of costs more than it should

### ISSUE THREAD

**Issue by NiChrosia** [franiscoder/dark-enchanting#13]
When enchanting boots with soul speed for example, it costs 1140 xp for the first level. Then, after purchasing the first level, the second level costs 2280, the cost it would take to get that from the start, instead of being another 1140. Same with the third level, it costs significantly more to purchase enchants level-by-level, rather than all at once.

**Comment by frqnny** [comment]
I'll look back at how we calculate that. Might want to save up XP then.

**Comment by frqnny** [comment]
I've decided that I like this. After all, it is that in vanilla that Enchantment I + Enchantment I = Enchantment 2. Also, there should be a small discount being applied iirc. I'll keep this issue open for me to see if that is not working or something
