### ISSUE TITLE
UI issue when used with All of Fabric 4 

### ISSUE THREAD

**Issue by Eddie-Carrizales** [franiscoder/dark-enchanting#14]
There is a UI issue in which the enchantments are behind the inventory items. So you cannot scroll or see the enchantments. I think its just a matter of adjusting the user interface in the mod or find out why its not compatible. The game does not crash, it just doest not display correctly.

**Comment by frqnny** [comment]
Mac?

**Comment by Eddie-Carrizales** [comment]
Yeah on mac

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by frqnny** [comment]
not my issue go to github.com/cottonmc/libgui

**Comment by Eddie-Carrizales** [comment]
Alrighty thanks tho!!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Eddie-Carrizales** [comment]
Hi, just wanted to say I managed to fix the issue by using RetiNO mod for minecraft. 
This had to do with how mac handles resolutions. :)
