### ISSUE TITLE
dark-enchanting-0.6.0-1.17.1 weapon crash

### ISSUE THREAD

**Issue by Koletan** [franiscoder/dark-enchanting#21]
dark-enchanting-0.6.0-1.17.1 chrashes the player interacting with the table whenever a weapon is placed into it, only weapons. That includes, axes, bows, swords, and tridents. tools and armor (excluding axes since they can receive weapon enchants) work perfectly fine.

**Comment by frqnny** [comment]
show crash since it works for me

**Comment by Koletan** [comment]
> show crash since it works for me

the thing is it doesn't give me a crash log, that's why I'm confused. It may be good to mention that I am on a server. It doesn't fully crash the game just boots me back to the main menu.

**Comment by Koletan** [comment]
[crash-2021-11-18_23.14.35-client.txt](https://github.com/frqnny/dark-enchanting/files/7585029/crash-2021-11-18_23.14.35-client.txt)

**Comment by Koletan** [comment]
I got it to give me a crash log

**Comment by frqnny** [comment]
spellbound issue
Check spellbound config, enable all the enchants 1.6.0 added a new experimental enchant disabled on default. Or disable em from showing up listing on dark enchanting config

**Comment by Koletan** [comment]
Gotcha, thank you. I'm not good at reading through crash logs and it was happening with the dark enchanter so I small brained and thought "well it must just be something with the mod itself" without thinking it could be some other mod causing the conflict.

**Comment by frqnny** [comment]
yeah the crash wouldn't tell you anything about the fact that it was spellbound, just former bug reports and testing. might look into it some more later to make better compat with spellbound
