### ISSUE TITLE
Disenchant discount

### ISSUE THREAD

**Issue by Flyvee** [franiscoder/dark-enchanting#23]
I constructed the dark shrine with a new dark enchanter while my old one no longer had any discount, but then I noticed that disenchanting items with the dark shrine dark enchanter gives half the exp than the one that has no discount, is this intentional that using the discount build at the price that disenchanting objects gives you less exp or is it a bug?

**Comment by frqnny** [comment]
yeah the dark shrine “tames” a tablle so that is intentional for now

**Comment by frqnny** [comment]
yeah the dark shrine “tames” a tablle so that is intentional for now
