### ISSUE TITLE
Discount when Disenchanting

### ISSUE THREAD

**Issue by BrotheBear** [franiscoder/dark-enchanting#26]
As said in the title.

The Dark Enchanter will give you a large amount of XP when disenchanting, however the upgraded version with the 20% discount actually gives you less XP when disenchanting rather than more.

I haven't tested it, but disenchanting with a normal dark enchanter + enchanting again with a fully upgraded dark enchanter is probably a good way to loop farm XP.

**Comment by frqnny** [comment]
intentional. shrine tames dark enchanter as part of lore
