### ISSUE TITLE
No bookshelf discount in 1.18.1

### ISSUE THREAD

**Issue by MadSiker1337** [franiscoder/dark-enchanting#27]
As said in the title, when I place bookshelves around the dark enchanter there is no discount. Here's an image of how I place it.
![Dark Enchanter Bookshelves](https://user-images.githubusercontent.com/67910050/146637072-a2637f70-50f0-4673-8c76-913de8c13891.png)
![image](https://user-images.githubusercontent.com/67910050/146637102-4b8bfe49-e16e-43e9-8350-a3ffbe776593.png)

I am using the mod within the modpack Better Minecraft
Everything else seems to be working.
Thanks

**Comment by frqnny** [comment]
check wiki

**Comment by MadSiker1337** [comment]
Where do I find it?

**Comment by frqnny** [comment]
check the wiki for information on how to access the wiki
