### ISSUE TITLE
Darkness enchants and LevelZ

### ISSUE THREAD

**Issue by xillenburg** [franiscoder/dark-enchanting#28]
Whenever I enchant something in the dark enchantment table, it also pulls out XP from my LevelZ XP. I've also contacted the LevelZ dev just in case it's his issue
![2021-12-20_12 02 28](https://user-images.githubusercontent.com/92593235/146712252-195a834e-5638-436e-b417-aa63999982dc.png)
.

**Comment by frqnny** [comment]
whats levelz

**Comment by xillenburg** [comment]
> whats levelz

RPG typa mod by globalZ
https://www.curseforge.com/minecraft/mc-mods/levelz
idk it feels like it's his issue but imma put it here just in case
