### ISSUE TITLE
Shift+click doesn't work on items

### ISSUE THREAD

**Issue by xillenburg** [franiscoder/dark-enchanting#31]
When I Shift+click on an item it doesn't go to the dark enchanting slot.

**Comment by JCastaneda-Dev** [comment]
that is not a feature

**Comment by frqnny** [comment]
yes it is in 0.6.3 pay attention keep up

**Comment by JCastaneda-Dev** [comment]
> 

dont know how

**Comment by frqnny** [comment]
just download my mods and you will be good in life
