### ISSUE TITLE
Config: Option to disable all Enchantments from a specific namespace

### ISSUE THREAD

**Issue by DaFuqs** [franiscoder/dark-enchanting#33]
The mod I am working on - Spectrum - uses a complex progression system for unloscking new Enchantments.

In Spectrum players are able to unlock new Enchantments as they progress though the mod. Having some of those enchantments available through the Dark Enchanter breaks this progression system big way.

There are other mods that use enchantments to add unique effects to a specific weapon, too. (liks MCDA)

It would be great to add an option to use namespaces in the blacklist. And even better if you shipped with "spectrum:*" added as a default. While I got a "check these things before you release this pack" page, nobody reads it anyways.

Always feel free to contact me here or on discord. I will be glad to help.

**Comment by frqnny** [comment]
dark enchanting imo should just not be loaded together then. should we mark each other as incompatibility?

**Comment by DaFuqs** [comment]
Since Spectrum does not touch vanilla and other modded enchants at all, but uses the unlocking mechanism just for its own, I can still very much see Dark Enchanting see being used for all other mods enchantment.

Marking the mods as incompatible would probably be a bit too much and limit modpack makers.

Do you have an interface maybe, or a tag where I can dynamically register stuff?

**Comment by frqnny** [comment]
I’ll see what I can do later

**Comment by theklos** [comment]
Is this fixed? Dark Enchanting completely breaks All of Fabric 5 by giving you *near* instant access to invincibility.

**Comment by frqnny** [comment]
they can literally just block each enchantment by name if necessary

**Comment by theklos** [comment]
Config doesn't work, so no we can't. Cant modify any individual enchantment.
