### ISSUE TITLE
Dark encanter ignores /experience commnad

### ISSUE THREAD

**Issue by vladislemon** [franiscoder/dark-enchanting#35]
Dark encanter ignores /experience commnad for some reason.
Only xp from orbs taken in account. I can't ecnhant items if i gave xp to player with a command and i can enchant items if i reseted xp with a command.
![image](https://user-images.githubusercontent.com/68472958/147604472-4544b0e3-e199-4660-af23-1308f4350849.png)

**Comment by frqnny** [comment]
The Dark Enchanter does not ignore the experience command, the experience command ignores the dark enchanter. Death to the Experience Command!

**Comment by frqnny** [comment]
In other words...
Vanilla Issue. Their own bad implementation of the command. Not mine.

**Comment by frqnny** [comment]
How about you stop cheating in your world >:)

**Comment by vladislemon** [comment]
> How about you stop cheating in your world >:)

I'm only testing features in my test world.

**Comment by JCastaneda-Dev** [comment]
simple, just add points and not levels
