### ISSUE TITLE
No Bookshelf Discount

### ISSUE THREAD

**Issue by DJMan255** [franiscoder/dark-enchanting#38]
I've got the normal arrangement of 15 bookshelves and its adding no discount, is more bookshelves needed or is the discount broken at the moment. 
Using the latest release of the mod on the Better Minecraft 1.18 modpack.

**Comment by frqnny** [comment]
chekc the wiki pls 😜

**Comment by JustZacTTv** [comment]
> chekc the wiki pls 😜
link?

**Comment by frqnny** [comment]
its right there in github, click the wiki tab

**Comment by JustZacTTv** [comment]
well i got your enchanting table but theres no such thing as a dark shrine
![2022-01-11_18 54 54](https://user-images.githubusercontent.com/65821001/149039896-c824eee3-ff7c-4ce5-b166-7b756e4a9cce.png)

**Comment by frqnny** [comment]
chekc the wiki last warning, you literally are not doing what im telling you its right there in this github

**Comment by JCastaneda-Dev** [comment]
https://github.com/frqnny/dark-enchanting/wiki
