### ISSUE TITLE
Enchanting an item with higher than max level enchants already applied resets them to max level

### ISSUE THREAD

**Issue by mcdnl90** [franiscoder/dark-enchanting#44]
This issue happened in a Better Minecraft modpack.
When you enchant an item that has an enchantment with higher a higher level than its normal maximum (like Power VI), all enchantments that are over its maximum get reset to that max level instead.

**Comment by Laifsyn** [comment]
That Looks ok for me. Unless you're using a mod which only provides over the level limit books(which they should´ve also add a max level edit at least optionally), then that would be more like a feature than anything.

Like you wanna give a player a special Sharpness 7 sword through a command. If he wanna do anything with it, he will lost said sword and can't recover it unless through some specific mod function.

One way to circumvent or solve this issue, just install "Limitless" and edit **ALL THE ENCHANTMENTS**. No slacking. You have to edit every single one enchantment, even for new ones, else you will have a 2^16-1 enchanting levels for each enchant book in the game. You just edit the game's enchant limit, ie from Power V to Power VI

**Comment by frqnny** [comment]
Perhaps I can add a custom "max" level field on the config that people can set for each enchantment. 

Edit: I'm probably going to make the check configurable.

**Comment by frqnny** [comment]
Fixed in dev, will have a configurable option in the next update
