### ISSUE TITLE
Suggestion: Mending Tweak

### ISSUE THREAD

**Issue by Laifsyn** [franiscoder/dark-enchanting#45]
Because 1 durability for 2 experience points is a bit too op in my opinion(wiki's Mending values). 
To put into perspective, one can get about 1300 experience points(~650 durability) in just under a minute with a Enderman farm. and if you lose 1 durability per hit (which is unlikely with unbreaking) then the 8 exp that an enderman drops would be enough is enough to pay repay 3 more hits (Not taking into account the efficient farms which are almost dozen kills per hit)

And furthermore ignoring other passive exp sources which won't spend any durability at all

**Comment by frqnny** [comment]
I don't want to tweak Mending, sorry.
