### ISSUE TITLE
Discount number seems incorrect

### ISSUE THREAD

**Issue by Suya1671** [franiscoder/dark-enchanting#50]
According to the wiki, the first layer has a discount of 20%, however Im only getting a 7% discount.

![image](https://user-images.githubusercontent.com/45307955/160877849-ce35cdf5-c13e-4840-933b-2a0136ddce36.png)
![image](https://user-images.githubusercontent.com/45307955/160877935-2cfe023b-64d4-4070-b7b2-ac89ed2c9808.png)

**Comment by JCastaneda-Dev** [comment]
are you using a pre created modpack

**Comment by Suya1671** [comment]
> are you using a pre created modpack

All of fabric 5

**Comment by JCastaneda-Dev** [comment]
The config had most likely been changed for balance reasons and that is why your discount is different from the wiki
