### ISSUE TITLE
Inconsistents Value Factors 

### ISSUE THREAD

**Issue by Laifsyn** [franiscoder/dark-enchanting#52]
So I'm having kinda of an issue getting exactly what're the values.

So the Receive Factor for enchantments is -1.5

so by that logic, if I have something that specifically costs 8891 to enchant, but the pay value to disenchant is 13 ,345. Even though close to 13,336, if there's no way to get how the values are calculated, then it's is really hard to fine tune the dark enchanting prices. Specially if you can't reload the Dark Enchant config file

the personal factors were all at 1.0

**Comment by frqnny** [comment]
please dont use negative values im not going to account for what that might do

**Comment by frqnny** [comment]
oh i get your concern. idk i just wrote the xp code to add and subtract stuff and multiply and divide and bam, it gets the amount. 

in other words, me or you or anybody trying to figure out exactly how i made the calculations is not the way to go

**Comment by Laifsyn** [comment]
so I gotta slam and reload individually until I'm satisfied with the price? x.x

**Comment by frqnny** [comment]
in all seriousness how much do you want it to be?…

**Comment by frqnny** [comment]
you can’t really reload the configs in game, it just wouldn’t work unless i rewrote config api completely

**Comment by Laifsyn** [comment]
just one example. I had the personalReceiveFactor set to 8.

Whatever was the value, I divided it by 8, then I supposdly I would get the base price(BasePrice). Then the cost would be> 
BasePrice*UnknownMultiplier=TargetPrice. If you give me ~10 mins I can try to get the exact numbers and the result of the calculation

**Comment by frqnny** [comment]
no im going to sleep
come
to my discord if you want to continue this conversation later
