### ISSUE TITLE
xp discount only going up to 40%

### ISSUE THREAD

**Issue by Crystaliii-i** [franiscoder/dark-enchanting#65]
the first time i build the shrine i got 50% ,
then i relocated it and rebuilt it exactly the same ,following the wiki both times, 
but this time the discount only goes up to 40% (the first layer with books should give 20% but it only gives 5% from my understanding of the wiki guide)

![Screenshot (3)](https://user-images.githubusercontent.com/78989374/188996724-cf6502f9-0f02-465b-b9b9-b5a7bde0bc70.png)
![Screenshot (2)](https://user-images.githubusercontent.com/78989374/188996730-6eac8136-e266-472a-92ef-b3720e75bf9d.png)

**Comment by ThomasJRyan** [comment]
I'm also having an issue with this. I followed the wiki, made the first ring, and it's only giving a 7% discount. On version 1.0.0+1.18.2

**Comment by frqnny** [comment]
Check your config, modpacks may change this setting sometimes.

**Comment by ThomasJRyan** [comment]
> 

Yyyyyyyyyup. You're right about that. Can't imagine why the modpack creator would do that 😑 Thank you for that and sorry to bother
