### ISSUE TITLE
Release for 19.2 

### ISSUE THREAD

**Issue by szekelymatyas** [franiscoder/dark-enchanting#67]
Can youe make an 19.2 release. Curseforge modpacks doesnt like 19.1, but im confident its working for 19.2 too.

**Comment by GhostIsBeHere** [comment]
I would also like to see it on 1.19.2 please!

**Comment by poly2it** [comment]
I can confirm that this mod works for 1.19.2. The developer just has to mark the files for that version on Modrinth and Curseforge.

**Comment by GhostIsBeHere** [comment]
Thank you!

**Comment by frqnny** [comment]
well i released a new version for it regardless so oh well
