### ISSUE TITLE
a way to un blacklist enchantments from mods

### ISSUE THREAD

**Issue by vsxgsonic** [franiscoder/dark-enchanting#68]
more of a question but how would I go about trying to re add(overwrite) a select few enchantments from a mod that has used the blacklist tag to remove them from the enchanter? any help would be apricated ..

**Comment by frqnny** [comment]
A mod uses datapacks to activate the blacklist. You can use datapack as well to either replace the tag completely and leave it empty, opting to just use the config. Or you can chose which are disabled via the tag instead of the config.

**Comment by vsxgsonic** [comment]
oh . I'm kind of new to the datapack stuff only just figured out how to add recipes ill be honest.

**Comment by frqnny** [comment]
it's for people who know their stuff. i may add an option later in the future that allows user to ignore the flag in the config, but for now you can figure out how to do it via datapacks.
