### ISSUE TITLE
Unexpected error "shaderinstance is null" 

### ISSUE THREAD

**Issue by personifiedmirror** [franiscoder/dark-enchanting#76]
Hello, I was trying to play minecraft with this mod on 1.19.4 but every time I loaded up a new world it would crash with this message: 
<img width="574" alt="Screen Shot 2023-05-06 at 11 20 34 AM" src="https://user-images.githubusercontent.com/132778261/236639512-fa65d5d9-941c-428e-841a-05ce535fab60.png">
Let me know if you need the crash report as well.

**Comment by personifiedmirror** [comment]
It could be due to my other mods installed but I'm not sure. I sort-of doubt that though because I tried it without the other mods and it did the same thing.

**Comment by frqnny** [comment]
we do not do anything with that
