### ISSUE TITLE
Opening Dark Enchanting Table Sometimes Removes EXP

### ISSUE THREAD

**Issue by milkev** [franiscoder/dark-enchanting#8]
Occassionally when I open the dark enchanting table it resets my exp levels. im on the latest version of fabric, fabric api, and dark enchanting as of this post. I haven't been able to find anything that links it to anything, not the circumstances for it to happen, or any logs or anything. This happens with both dedicated servers and singleplayer worlds. My dark enchanting table does not have any bookshelves available to it.

my mod list, I would test if its a mod compatability, but with no way to intentionally activate this, and it being quite rare, it would take quite a while to test. if there is one you know that is incompatable or something.
[](https://pastebin.com/u0KQh8Gs )

**Comment by frqnny** [comment]
Thanks for the report! If you are able to replicate it again, please tell me. Are you sure it reset it and did not fix itself later on? What buttons were you touching? There has to be a pattern. Thanks!

**Comment by milkev** [comment]
it completely resets my levels and i never regain them. I can relog and they are still removed. 
Its happened 2 out of the 6 or so times ive opened the dark enchanting table so far, I'll be paying more attention to find any links in whats causing it, and report here if I find anything.
I just used right click to open the gui.

**Comment by frqnny** [comment]
That's very weird. The only time we touch player levels is when you press the buttons to enchant/repair.

**Comment by milkev** [comment]
terribly sorry, it seems to be an issue with cross-dimensional teleporting with fabricHomes. I thought it was dark enchanting bcus i only ever noticed it when i opened the dark enchanting table ;-;
i smart i promise. sorry about this!
