### ISSUE TITLE
RESOLVED: Crash on 1.20.6; UPDATE FABRIC API

### ISSUE THREAD

**Issue by ArnoFanrce** [franiscoder/dark-enchanting#87]
[错误报告-2024-6-20_12.49.09.zip](https://github.com/user-attachments/files/15908766/-2024-6-20_12.49.09.zip)
1.20.6farbic，Crash during use，
I don't know why, I'm requesting help

**Comment by frqnny** [comment]
Hey, I am not at my computer to be able to see that but having seen an earlier crash, update Fabric API and see if that fixes it!

**Comment by frqnny** [comment]
Oh, I can open it with my phone. 

I can 100% tell you: update Fabric API. Please tell me if you have more issues, thank you!
