### ISSUE TITLE
Incompatible with Mo' Structures

### ISSUE THREAD

**Issue by NattoRiisa** [franiscoder/dark-enchanting#88]
Unaware on where to report this since this is one of the mod that uses the config,, but ..?

Uncaught exception in thread "main"
java.lang.RuntimeException: Non-unique Mixin config name omega-config.mixins.json used by the mods omega-config and omegaconfig
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:91)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

modlist btw
accurate-block-placement-1.2.5.jar
AchievementOptimizer-fabric-1.21-1.1.0.jar
Amplified_Nether_1.21_v1.2.5.jar
animatica-0.6.1+1.21.jar
appleskin-fabric-mc1.21-3.0.2.jar
architectury-13.0.1-fabric.jar
auto-plant-crops-1.3.jar
AxesAreWeapons-1.9.0-fabric-1.21.jar
BadOptimizations-2.1.4-1.21.jar
balm-fabric-1.21-21.0.7.jar
BetterF3-11.0.1-Fabric-1.21.jar
BetterFurnace-V1.2.0.zip
betterimpaling-3.0+1.21.jar
beyondenchant-1.2.0.jar
blastingraw-1.21-2-fabric.jar
blastingsand-1.21-11-fabric.jar
BoostedExperience-1.1.1.jar
brb-1.10.0+1.21.jar
c2me-fabric-mc1.21-0.2.0+alpha.11.101.jar
chesttracker-2.4.7+1.21.jar
clientsidenoteblocks-2.8.jar
cloth-config-15.0.127-fabric.jar
Clumps-fabric-1.21-18.0.0.1.jar
collective-1.21.0-7.62.jar
compact_storage-1.21-fabric-8.0.74.jar
continuity-3.0.0-beta.5+1.21.jar
craft-spawn-eggs-v.2.0.0.jar
craftable_enchanted_golden_apple-1.0.7.jar
craftingtweaks-fabric-1.21-21.0.3.jar
cullleaves-fabric-3.4.0.jar
darkenchanting-fabric-1.2.0.jar
Debugify-1.21+1.0.jar
dynamiccrosshair-8.0.2+1.21-fabric.jar
EasyVillagerTrade-1.2-1.21.jar
eg_fix_horizontal_camera_lag-1.0.1.jar
emi-1.1.7+1.21+fabric.jar
enchantments-encore-1.2a.jar
enhancedblockentities-0.10.1+1.21.jar
entityculling-fabric-1.6.6-mc1.21.jar
entity_model_features_fabric_1.21-pre3-test.jar
entity_texture_features_fabric_1.21-6.1.1.jar
expanded-armor-enchanting-1.0.8.jar
expanded-axe-enchanting-1.0.9.jar
expanded-bow-enchanting-1.1.0.jar
expanded-crossbow-enchanting-1.0.0.jar
expanded-trident-enchanting-1.0.9.jar
expanded-weapon-enchanting-1.0.8.jar
expandedstorage-14.0.0+1.21-pre2-fabric.jar
Explorify v1.5.0 f10-48.jar
fabric-api-0.100.3+1.21.jar
fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar
FabricBetterGrass-1.0.14+1.21.jar
FallingTree-1.21-1.21.0.2.jar
fasterrandom-4.1.0.jar
fasttrading-0.1.4+1.21.jar
ferritecore-7.0.0-fabric.jar
FeyTweaks-1.21-1.2.8.jar
ForgeConfigAPIPort-v21.0.0-1.21-Fabric.jar
frost-2.0.1.jar
FuelInfo-2.1+1.21.jar
GameClock-1.2.0.jar
held-item-info-1.7.0.jar
HigherNether-1.0.2.jar
highspeed-rail-0.8.0+1.21.jar
HopoBetterMineshaft-[1.21]-1.2.4.jar
HopoBetterRuinedPortals-[1.21]-1.4.2.jar
HopoBetterUnderwaterRuins-[1.21]-1.1.8.jar
idwtialsimmoedm-0.3.0+1.21.jar
ImmediatelyFast-Fabric-1.2.18+1.21.jar
indium-1.0.33+mc1.21.jar
infinitetrading-1.21.0-4.4.jar
InventoryProfilesNext-fabric-1.21-2.0.0.jar
iris-1.7.1+mc1.21.jar
ironbookshelves-1.21-1.3.1-fabric.jar
ironladders-mod-1.21-2.2.3-fabric.jar
Jade-1.21-Fabric-15.0.4.jar
katters-structures-1.10.jar
language-reload-1.6.1+1.21.jar
larger-ore-veins-deluxe-1.2.2.jar
liberty-villagers-mod-1.0.15+fabric+1.21.jar
libIPN-fabric-1.21-5.0.0.jar
lithium-fabric-mc1.21-0.12.7.jar
longbooks-1.0+1.21.jar
midnightlib-fabric-1.5.7.jar
mine-treasure-1.4.3.jar
modelfix-1.21-1.6-fabric.jar
moderner-beta-fabric-6.5+er1.3.1+1.21.jar
modernfix-fabric-5.18.3+mc1.21.jar
modmenu-11.0.0.jar
moreores+-2.1+1.21.jar
mostructures-1.4.8+1.21.jar
neoenchant-5.2.2.jar
Nullscape_1.21_v1.2.6.jar
obsidianequipment-v1.0.0-fabric-1.21.jar
ObsidianUI-fabric-0.2.6+mc1.21.jar
optigui-2.3.0-beta.2+1.21.jar
owo.txt
Philips-Ruins1.21-1.2[Fabric].jar
PresenceFootsteps-1.10.0+1.21.jar
puzzle-1.6.3+1.21.jar
qraftyfied-8.0.1.jar
qraftys-japanese-villages-2.2.jar
recast-1.21.0-3.4.jar
reeses_sodium_options-1.7.2+mc1.21.jar
repurposed_structures-7.5.2+1.21-fabric.jar
rmes-campfire-leather-1.1.5.jar
RoguelikeDungeons-2.0.7-1.21-fabric.jar
Rose-Bush-1.1.1.jar
RyoamicLights-fabric-0.2.7+mc1.21.jar
simple-hud-enhanced+1.21-4.7.0.jar
SimpleCopperPipes-2.0.jar
skinlayers3d-fabric-1.6.6-mc1.21.jar
smeltingstone-1.21-0-fabric.jar
sodium-extra-0.5.7+mc1.21.jar
sodium-fabric-0.5.9+mc1.21.jar
sound-physics-remastered-fabric-1.21-1.4.3.jar
stackcalc-revived-1.1.1.jar
status-effect-bars-1.0.6.jar
TaxFreeLevels-1.3.12-fabric-1.20.5.jar
tru.e-ending-v1.1.1.jar
ukulib-1.4.0+1.21.jar
unwrecked-ships-plus-2.0.0.jar
VanillaIcecreamFix-1.2.2-beta.jar
village-hero-plus-2.1.jar
waystones-fabric-1.21-21.0.2.jar
XaerosWorldMap_1.38.8_Fabric_1.21.jar
Xaeros_Minimap_24.2.1_Fabric_1.21.jar
xtraarrows-3.3-fabric-mc1.21.jar
YetAnotherConfigLib-3.5.0+1.21-fabric.jar
yggdrasil-structure-1.2.0.jar
your-reputation-0.2.6+jade.1.21.jar
Zoomify-2.14.0+1.21.jar

**Comment by NattoRiisa** [comment]
ah... looks like i found a root cause

**Comment by frqnny** [comment]
Working on a build to release right now! I can give you a jar to test in my Discord

**Comment by frqnny** [comment]
Please update Mo' Structures:
https://www.curseforge.com/minecraft/mc-mods/mo-structures

**Comment by NattoRiisa** [comment]
thank you!
